import { createServerFn } from "@tanstack/react-start";
import OpenAI from "openai";

const MODEL = "openai/gpt-oss-20b";

export type AiStatus = {
  aiMode: boolean;
  model: string;
  reason: string;
};

/**
 * Checks whether the server has access to the Groq API key.
 * The API key never reaches the browser.
 */
export const getAiStatus = createServerFn({ method: "GET" }).handler(
  async (): Promise<AiStatus> => {
    const key = process.env["GROQ_API_KEY"];

    return {
      aiMode: Boolean(key),
      model: MODEL,
      reason: key
        ? "Server-side Groq calls are enabled for the agent pipeline."
        : "No Groq API key configured — running the deterministic demo pipeline.",
    };
  },
);

/**
 * Sends a prompt to Groq from the server.
 * The API key is never exposed to the client.
 */
export const enrichWithAi = createServerFn({ method: "POST" })
  .validator((input: { prompt: string }) => input)
  .handler(async ({ data }) => {
    const key = process.env["GROQ_API_KEY"];

    if (!key) {
      return {
        aiMode: false,
        text: "",
        note: "Demo Mode — no Groq API key configured.",
      };
    }

    try {
      const client = new OpenAI({
        apiKey: key,
        baseURL: "https://api.groq.com/openai/v1",
      });

      const response = await client.responses.create({
        model: MODEL,
        instructions:
          "You are an AI assistant for a recruitment platform. Analyze the provided information carefully and return clear, factual, evidence-based results. Do not invent candidate information.",
        input: data.prompt,
      });

      return {
        aiMode: true,
        text: response.output_text,
        note: "AI Mode — response generated by Groq.",
      };
    } catch (error) {
      console.error("Groq request failed:", error);

      return {
        aiMode: true,
        text: "",
        note: "Groq request failed. Check the server logs.",
      };
    }
  });

export type ExtractedFile = {
  fileName: string;
  fileType: "pdf" | "docx" | "txt";
  text: string;
};

/**
 * Reads an uploaded document on the server and returns its text.
 *
 * The browser sends the file as base64.
 * PDF/DOCX parsing happens only on the server.
 */
export const extractUploadedFile = createServerFn({ method: "POST" })
  .validator(
    (input: {
      fileName: string;
      fileType: "pdf" | "docx" | "txt";
      base64: string;
    }) => input,
  )
  .handler(async ({ data }): Promise<ExtractedFile> => {
    const buffer = Buffer.from(data.base64, "base64");

    let text = "";

    if (data.fileType === "txt") {
      text = buffer.toString("utf-8");
    }

    if (data.fileType === "pdf") {
      const { PDFParse } = await import("pdf-parse");

      const parser = new PDFParse({
        data: buffer,
      });

      const result = await parser.getText();

      text = result.text;

      await parser.destroy();
    }

    if (data.fileType === "docx") {
      const mammoth = await import("mammoth");

      const result = await mammoth.extractRawText({
        buffer,
      });

      text = result.value;
    }

    if (!text.trim()) {
      throw new Error(
        `No readable text could be extracted from ${data.fileName}.`,
      );
    }

    return {
      fileName: data.fileName,
      fileType: data.fileType,
      text: text.trim(),
    };
  });

/* =========================================================
   RESUME AGENT
   ========================================================= */

export type ResumeAgentResult = {
  isResume: boolean;
  confidence: number;
  name: string;
  email: string;
  phone: string;
  location: string;
  title: string;
  years: number;

  skills: string[];

  education: {
    degree: string;
    level: "PhD" | "Masters" | "Bachelors" | "Diploma";
    field: string;
    school: string;
    year: number;
  };

  experience: {
    company: string;
    role: string;
    start: string;
    end: string;
    years: number;
    bullets: string[];
  }[];

  projects: {
    name: string;
    description: string;
    skills: string[];
  }[];

  certifications: string[];

  summary: string;

  suggestions: string[];
};

/**
 * Resume Agent
 *
 * Takes extracted resume text and converts it into
 * structured candidate information.
 */
export const runResumeAgent = createServerFn({ method: "POST" })
  .validator(
    (input: {
      fileName: string;
      text: string;
    }) => input,
  )
  .handler(async ({ data }): Promise<ResumeAgentResult> => {
    const key = process.env["GROQ_API_KEY"];

    if (!key) {
      throw new Error("GROQ_API_KEY is not configured on the server.");
    }

    const client = new OpenAI({
      apiKey: key,
      baseURL: "https://api.groq.com/openai/v1",
    });

    const response = await client.responses.create({
      model: MODEL,

      instructions: `
You are the Resume Agent in a multi-agent recruitment platform.

Your job is to carefully analyze the supplied document text.

First determine whether the document is actually a resume or CV.

If it is NOT a resume:
- isResume must be false
- do not invent candidate information
- confidence should reflect your certainty
- suggestions should explain what type of document was detected

If it IS a resume:
- extract only information supported by the document
- never invent missing information
- use empty strings, empty arrays, or 0 when information is unavailable
- normalize skills into clear names
- calculate years of experience only when it can reasonably be determined
- summarize the candidate using evidence from the resume
- provide useful suggestions for recruiter review

Return ONLY the requested structured data.
`,

      input: `
File name: ${data.fileName}

Resume/document text:

${data.text}
`,

      text: {
        format: {
          type: "json_schema",
          name: "resume_agent_result",
          strict: true,

          schema: {
            type: "object",

            properties: {
              isResume: {
                type: "boolean",
              },

              confidence: {
                type: "number",
              },

              name: {
                type: "string",
              },

              email: {
                type: "string",
              },

              phone: {
                type: "string",
              },

              location: {
                type: "string",
              },

              title: {
                type: "string",
              },

              years: {
                type: "number",
              },

              skills: {
                type: "array",
                items: {
                  type: "string",
                },
              },

              education: {
                type: "object",

                properties: {
                  degree: {
                    type: "string",
                  },

                  level: {
                    type: "string",
                    enum: [
                      "PhD",
                      "Masters",
                      "Bachelors",
                      "Diploma",
                    ],
                  },

                  field: {
                    type: "string",
                  },

                  school: {
                    type: "string",
                  },

                  year: {
                    type: "number",
                  },
                },

                required: [
                  "degree",
                  "level",
                  "field",
                  "school",
                  "year",
                ],

                additionalProperties: false,
              },

              experience: {
                type: "array",

                items: {
                  type: "object",

                  properties: {
                    company: {
                      type: "string",
                    },

                    role: {
                      type: "string",
                    },

                    start: {
                      type: "string",
                    },

                    end: {
                      type: "string",
                    },

                    years: {
                      type: "number",
                    },

                    bullets: {
                      type: "array",
                      items: {
                        type: "string",
                      },
                    },
                  },

                  required: [
                    "company",
                    "role",
                    "start",
                    "end",
                    "years",
                    "bullets",
                  ],

                  additionalProperties: false,
                },
              },

              projects: {
                type: "array",

                items: {
                  type: "object",

                  properties: {
                    name: {
                      type: "string",
                    },

                    description: {
                      type: "string",
                    },

                    skills: {
                      type: "array",
                      items: {
                        type: "string",
                      },
                    },
                  },

                  required: [
                    "name",
                    "description",
                    "skills",
                  ],

                  additionalProperties: false,
                },
              },

              certifications: {
                type: "array",

                items: {
                  type: "string",
                },
              },

              summary: {
                type: "string",
              },

              suggestions: {
                type: "array",

                items: {
                  type: "string",
                },
              },
            },

            required: [
              "isResume",
              "confidence",
              "name",
              "email",
              "phone",
              "location",
              "title",
              "years",
              "skills",
              "education",
              "experience",
              "projects",
              "certifications",
              "summary",
              "suggestions",
            ],

            additionalProperties: false,
          },
        },
      },
    });

    return JSON.parse(response.output_text) as ResumeAgentResult;
  });

/* =========================================================
   JOB AGENT
   ========================================================= */

export type JobAgentResult = {
  isJobDescription: boolean;
  confidence: number;

  title: string;
  department: string;
  location: string;
  employmentType: string;

  description: string;

  minYears: number;

  mustHave: string[];
  niceToHave: string[];

  responsibilities: string[];

  educationLevel:
    | "PhD"
    | "Masters"
    | "Bachelors"
    | "Diploma";

  educationField: string;

  certifications: string[];

  projectKeywords: string[];

  suggestions: string[];
};

/**
 * Job Agent
 *
 * Takes a job description and converts it into
 * structured recruitment requirements.
 */
export const runJobAgent = createServerFn({ method: "POST" })
  .validator(
    (input: {
      title: string;
      text: string;
    }) => input,
  )
  .handler(
    async ({
      data,
    }: {
      data: {
        title: string;
        text: string;
      };
    }): Promise<JobAgentResult> => {
      const key = process.env["GROQ_API_KEY"];

      if (!key) {
        throw new Error(
          "GROQ_API_KEY is not configured on the server.",
        );
      }

      const client = new OpenAI({
        apiKey: key,
        baseURL: "https://api.groq.com/openai/v1",
      });

      const response = await client.responses.create({
        model: MODEL,

        instructions: `
You are the Job Agent in a multi-agent recruitment platform.

Your job is to analyze a supplied job description and convert it
into structured recruitment requirements.

First determine whether the supplied text is actually a job
description or job specification.

If it is NOT a job description:
- isJobDescription must be false
- do not invent job information
- confidence should reflect your certainty
- suggestions should explain what type of document was detected

If it IS a job description:
- extract only information supported by the job description
- never invent requirements
- use empty strings, empty arrays, or 0 when information is unavailable
- identify the minimum years of experience
- separate MUST-HAVE requirements from NICE-TO-HAVE requirements
- extract responsibilities
- identify education requirements
- identify certifications
- identify project-related keywords
- preserve important technical skills
- normalize skill names into clear names
- provide useful suggestions for recruiter review

Important:
- Do not treat every mentioned technology as a must-have.
- Explicitly required skills should be must-have.
- Preferred, bonus, plus, or nice-to-have skills should be nice-to-have.
- If the job description does not clearly distinguish them,
  use reasonable evidence from wording.
- Do not create requirements that are not supported by the text.

Return ONLY the requested structured data.
`,

        input: `
Job title supplied by recruiter:

${data.title}

Job description:

${data.text}
`,

        text: {
          format: {
            type: "json_schema",
            name: "job_agent_result",
            strict: true,

            schema: {
              type: "object",

              properties: {
                isJobDescription: {
                  type: "boolean",
                },

                confidence: {
                  type: "number",
                },

                title: {
                  type: "string",
                },

                department: {
                  type: "string",
                },

                location: {
                  type: "string",
                },

                employmentType: {
                  type: "string",
                },

                description: {
                  type: "string",
                },

                minYears: {
                  type: "number",
                },

                mustHave: {
                  type: "array",
                  items: {
                    type: "string",
                  },
                },

                niceToHave: {
                  type: "array",
                  items: {
                    type: "string",
                  },
                },

                responsibilities: {
                  type: "array",
                  items: {
                    type: "string",
                  },
                },

                educationLevel: {
                  type: "string",
                  enum: [
                    "PhD",
                    "Masters",
                    "Bachelors",
                    "Diploma",
                  ],
                },

                educationField: {
                  type: "string",
                },

                certifications: {
                  type: "array",
                  items: {
                    type: "string",
                  },
                },

                projectKeywords: {
                  type: "array",
                  items: {
                    type: "string",
                  },
                },

                suggestions: {
                  type: "array",
                  items: {
                    type: "string",
                  },
                },
              },

              required: [
                "isJobDescription",
                "confidence",
                "title",
                "department",
                "location",
                "employmentType",
                "description",
                "minYears",
                "mustHave",
                "niceToHave",
                "responsibilities",
                "educationLevel",
                "educationField",
                "certifications",
                "projectKeywords",
                "suggestions",
              ],

              additionalProperties: false,
            },
          },
        },
      });

      return JSON.parse(
        response.output_text,
      ) as JobAgentResult;
    },
  );