import type { Candidate, Job } from "./types";

export const SEED_JOBS: Job[] = [
  {
    id: "job-mle",
    title: "Machine Learning Engineer",
    department: "AI Platform",
    location: "Bengaluru, IN (Hybrid)",
    employmentType: "Full-time",
    description:
      "We are hiring a Machine Learning Engineer to own the training, evaluation and deployment of production models across our recommendation and ranking surfaces. You will partner with product and platform teams to move models from notebook to reliable, monitored services.",
    minYears: 4,
    mustHave: ["Python", "PyTorch", "Machine Learning", "MLOps", "Docker", "SQL"],
    niceToHave: ["Kubernetes", "AWS SageMaker", "Feature Store", "Spark", "Airflow"],
    responsibilities: [
      "Design and train deep learning models for ranking and recommendation",
      "Deploy models as scalable services with monitoring and rollback",
      "Build reproducible training pipelines and feature engineering workflows",
      "Collaborate with product teams to define offline and online metrics",
      "Optimise model inference latency and infrastructure cost",
    ],
    educationLevel: "Bachelors",
    educationField: "Computer Science",
    certifications: ["AWS Certified Machine Learning", "TensorFlow Developer Certificate"],
    projectKeywords: ["recommendation", "deep learning", "deployment", "pipeline", "inference"],
    source: "seed",
  },
  {
    id: "job-ds",
    title: "Data Scientist",
    department: "Growth Analytics",
    location: "Remote, IN",
    employmentType: "Full-time",
    description:
      "As a Data Scientist you will turn messy behavioural data into decisions: experiment design, causal analysis, forecasting and executive-ready storytelling for the growth organisation.",
    minYears: 3,
    mustHave: ["Python", "SQL", "Statistics", "A/B Testing", "Data Visualization"],
    niceToHave: ["R", "Causal Inference", "Tableau", "Forecasting", "dbt"],
    responsibilities: [
      "Design and analyse controlled experiments across growth surfaces",
      "Build forecasting and cohort models for retention and revenue",
      "Develop dashboards and reporting for executive stakeholders",
      "Partner with engineering on event instrumentation and data quality",
    ],
    educationLevel: "Masters",
    educationField: "Statistics",
    certifications: ["Google Data Analytics", "Microsoft Certified: Azure Data Scientist"],
    projectKeywords: ["experiment", "forecasting", "dashboard", "churn", "segmentation"],
    source: "seed",
  },
  {
    id: "job-nlp",
    title: "AI/NLP Engineer",
    department: "Applied AI",
    location: "Hyderabad, IN (Onsite)",
    employmentType: "Full-time",
    description:
      "Join the Applied AI team building retrieval-augmented assistants, document understanding and evaluation harnesses on top of large language models used by thousands of enterprise users daily.",
    minYears: 3,
    mustHave: ["Python", "NLP", "Transformers", "LLM", "Vector Databases"],
    niceToHave: ["LangChain", "RAG", "Prompt Engineering", "Hugging Face", "Fine-tuning"],
    responsibilities: [
      "Build retrieval augmented generation pipelines over enterprise documents",
      "Fine-tune and evaluate transformer models for domain tasks",
      "Design evaluation harnesses measuring hallucination and grounding quality",
      "Ship low latency inference endpoints for language features",
    ],
    educationLevel: "Bachelors",
    educationField: "Computer Science",
    certifications: ["DeepLearning.AI NLP Specialization"],
    projectKeywords: ["chatbot", "retrieval", "transformer", "embedding", "summarization"],
    source: "seed",
  },
];

function c(x: Candidate): Candidate {
  return x;
}

export const SEED_CANDIDATES: Candidate[] = [
  c({
    id: "cand-1",
    name: "Aarav Mehta",
    email: "aarav.mehta@example.com",
    phone: "+91 98200 11223",
    location: "Bengaluru, IN",
    age: 31,
    gender: "Male",
    title: "Senior Machine Learning Engineer",
    years: 7,
    summary:
      "Senior Machine Learning Engineer with 7 years building large scale recommendation and ranking systems in Python and PyTorch, with strong MLOps ownership from training pipeline to monitored deployment.",
    skills: [
      "Python", "PyTorch", "Machine Learning", "MLOps", "Docker", "Kubernetes", "SQL", "Spark", "Airflow", "AWS SageMaker", "Feature Store",
    ],
    education: {
      degree: "M.Tech",
      level: "Masters",
      field: "Computer Science",
      school: "IIT Bombay",
      year: 2018,
    },
    experience: [
      {
        company: "Flipkart",
        role: "Senior Machine Learning Engineer",
        start: "2021",
        end: "Present",
        years: 4,
        bullets: [
          "Designed and trained deep learning models for ranking and recommendation serving 40M daily users, lifting CTR by 12%.",
          "Deployed models as scalable services with monitoring and rollback using Docker, Kubernetes and Seldon.",
          "Built reproducible training pipelines and feature engineering workflows on Spark and Airflow.",
          "Optimised model inference latency from 180ms to 45ms through quantisation and batching.",
        ],
      },
      {
        company: "Swiggy",
        role: "Machine Learning Engineer",
        start: "2018",
        end: "2021",
        years: 3,
        bullets: [
          "Built demand forecasting models in PyTorch used for rider allocation across 200 cities.",
          "Collaborated with product teams to define offline and online metrics for delivery ETA models.",
        ],
      },
    ],
    projects: [
      {
        name: "RankFlow",
        description:
          "An end-to-end recommendation and deep learning deployment pipeline with automated retraining and inference benchmarking.",
        skills: ["PyTorch", "Airflow", "Docker"],
      },
      {
        name: "FeatureHub",
        description: "Internal feature store powering 60+ production models with point-in-time correctness.",
        skills: ["Spark", "SQL", "Feature Store"],
      },
    ],
    certifications: ["AWS Certified Machine Learning", "Certified Kubernetes Administrator"],
    source: "seed",
  }),
  c({
    id: "cand-2",
    name: "Priya Raghavan",
    email: "priya.raghavan@example.com",
    phone: "+91 99401 55210",
    location: "Chennai, IN",
    age: 29,
    gender: "Female",
    title: "Data Scientist",
    years: 5,
    summary:
      "Data Scientist specialising in experimentation and causal inference, with a Masters in Statistics and five years of A/B testing and forecasting work for consumer subscription products.",
    skills: [
      "Python", "SQL", "Statistics", "A/B Testing", "Data Visualization", "Causal Inference", "R", "Forecasting", "Tableau", "dbt",
    ],
    education: {
      degree: "M.Sc",
      level: "Masters",
      field: "Statistics",
      school: "ISI Kolkata",
      year: 2020,
    },
    experience: [
      {
        company: "Zomato",
        role: "Data Scientist",
        start: "2022",
        end: "Present",
        years: 3,
        bullets: [
          "Designed and analysed controlled experiments across growth surfaces, running 120+ A/B tests annually.",
          "Built forecasting and cohort models for retention and revenue guiding a 9% subscription lift.",
          "Developed dashboards and reporting for executive stakeholders in Tableau.",
        ],
      },
      {
        company: "Freshworks",
        role: "Analytics Associate",
        start: "2020",
        end: "2022",
        years: 2,
        bullets: [
          "Partnered with engineering on event instrumentation and data quality for 30 product surfaces.",
          "Applied causal inference to isolate pricing impact on churn using difference-in-differences.",
        ],
      },
    ],
    projects: [
      {
        name: "ChurnLens",
        description: "Churn segmentation and forecasting toolkit with a self-serve dashboard for growth managers.",
        skills: ["Python", "SQL", "Tableau"],
      },
      {
        name: "ExperimentDesk",
        description: "Internal experiment registry with automated sequential testing and guardrail alerts.",
        skills: ["Statistics", "A/B Testing"],
      },
    ],
    certifications: ["Google Data Analytics"],
    source: "seed",
  }),
  c({
    id: "cand-3",
    name: "Rohan Kulkarni",
    email: "rohan.kulkarni@example.com",
    phone: "+91 90040 77812",
    location: "Pune, IN",
    age: 27,
    gender: "Male",
    title: "NLP Engineer",
    years: 4,
    summary:
      "NLP Engineer focused on retrieval augmented generation, transformer fine-tuning and evaluation harnesses for enterprise document assistants.",
    skills: [
      "Python", "NLP", "Transformers", "LLM", "Vector Databases", "LangChain", "RAG", "Prompt Engineering", "Hugging Face", "Fine-tuning", "PyTorch",
    ],
    education: {
      degree: "B.Tech",
      level: "Bachelors",
      field: "Computer Science",
      school: "COEP Pune",
      year: 2021,
    },
    experience: [
      {
        company: "Observe.ai",
        role: "NLP Engineer",
        start: "2022",
        end: "Present",
        years: 3,
        bullets: [
          "Built retrieval augmented generation pipelines over enterprise documents with Pinecone and LangChain.",
          "Fine-tuned and evaluated transformer models for domain tasks, improving F1 from 0.71 to 0.86.",
          "Designed evaluation harnesses measuring hallucination and grounding quality across 4 assistants.",
          "Shipped low latency inference endpoints for language features at 120 QPS.",
        ],
      },
      {
        company: "Persistent Systems",
        role: "ML Associate",
        start: "2021",
        end: "2022",
        years: 1,
        bullets: ["Developed summarization models for contract review using Hugging Face transformers."],
      },
    ],
    projects: [
      {
        name: "DocPilot",
        description:
          "A retrieval chatbot over 2M enterprise documents using embedding search, reranking and grounded summarization.",
        skills: ["LLM", "Vector Databases", "RAG"],
      },
      {
        name: "EvalHarness",
        description: "Open-source transformer evaluation suite for hallucination scoring.",
        skills: ["Transformers", "Python"],
      },
    ],
    certifications: ["DeepLearning.AI NLP Specialization"],
    source: "seed",
  }),
  c({
    id: "cand-4",
    name: "Sneha Iyer",
    email: "sneha.iyer@example.com",
    phone: "+91 97311 20984",
    location: "Bengaluru, IN",
    age: 33,
    gender: "Female",
    title: "Lead Data Scientist",
    years: 9,
    summary:
      "Lead Data Scientist with nine years across marketplace pricing, forecasting and experimentation, now leading a team of six analysts and scientists.",
    skills: [
      "Python", "SQL", "Statistics", "A/B Testing", "Forecasting", "Data Visualization", "Spark", "Machine Learning", "Tableau",
    ],
    education: {
      degree: "PhD",
      level: "PhD",
      field: "Applied Statistics",
      school: "IIM Bangalore",
      year: 2016,
    },
    experience: [
      {
        company: "Ola",
        role: "Lead Data Scientist",
        start: "2019",
        end: "Present",
        years: 6,
        bullets: [
          "Built forecasting and cohort models for retention and revenue across 8 markets.",
          "Designed and analysed controlled experiments across growth surfaces including surge pricing.",
          "Developed dashboards and reporting for executive stakeholders reviewed weekly by the CEO.",
        ],
      },
      {
        company: "Mu Sigma",
        role: "Decision Scientist",
        start: "2016",
        end: "2019",
        years: 3,
        bullets: ["Delivered demand segmentation and churn analytics for retail clients."],
      },
    ],
    projects: [
      {
        name: "SurgeSim",
        description: "Simulation platform for pricing experiments with cohort segmentation and revenue forecasting.",
        skills: ["Python", "Statistics"],
      },
    ],
    certifications: ["Microsoft Certified: Azure Data Scientist"],
    source: "seed",
  }),
  c({
    id: "cand-5",
    name: "Vikram Desai",
    email: "vikram.desai@example.com",
    phone: "+91 98860 30045",
    location: "Mumbai, IN",
    age: 25,
    gender: "Male",
    title: "Junior Data Analyst",
    years: 2,
    summary:
      "Analyst two years into a career in reporting and dashboarding, currently self-studying machine learning and Python automation.",
    skills: ["SQL", "Excel", "Data Visualization", "Python", "Power BI"],
    education: {
      degree: "B.Com",
      level: "Bachelors",
      field: "Commerce",
      school: "NMIMS Mumbai",
      year: 2023,
    },
    experience: [
      {
        company: "HDFC Bank",
        role: "Data Analyst",
        start: "2023",
        end: "Present",
        years: 2,
        bullets: [
          "Developed dashboards and reporting for executive stakeholders across retail lending.",
          "Automated weekly SQL extracts, saving 12 hours of manual reporting per week.",
        ],
      },
    ],
    projects: [
      {
        name: "LoanBoard",
        description: "Power BI dashboard tracking loan portfolio health with drill-down segmentation.",
        skills: ["Power BI", "SQL"],
      },
    ],
    certifications: [],
    source: "seed",
  }),
  c({
    id: "cand-6",
    name: "Ananya Bose",
    email: "ananya.bose@example.com",
    phone: "+91 98311 66702",
    location: "Kolkata, IN",
    age: 30,
    gender: "Female",
    title: "Applied Scientist, NLP",
    years: 6,
    summary:
      "Applied Scientist working on multilingual language models, embeddings and summarization for a global publishing platform.",
    skills: [
      "Python", "NLP", "Transformers", "LLM", "Hugging Face", "Fine-tuning", "PyTorch", "Machine Learning", "Docker",
    ],
    education: {
      degree: "M.S",
      level: "Masters",
      field: "Computational Linguistics",
      school: "IIIT Hyderabad",
      year: 2019,
    },
    experience: [
      {
        company: "Wiley",
        role: "Applied Scientist",
        start: "2021",
        end: "Present",
        years: 4,
        bullets: [
          "Fine-tuned and evaluated transformer models for domain tasks across 11 languages.",
          "Shipped low latency inference endpoints for language features used in editorial tooling.",
          "Designed evaluation harnesses measuring hallucination and grounding quality for summarization.",
        ],
      },
      {
        company: "TCS Research",
        role: "Research Engineer",
        start: "2019",
        end: "2021",
        years: 2,
        bullets: ["Published work on embedding compression for low-resource Indic languages."],
      },
    ],
    projects: [
      {
        name: "PolyGloss",
        description: "Multilingual embedding and summarization service backing editorial search.",
        skills: ["Transformers", "NLP"],
      },
    ],
    certifications: ["DeepLearning.AI NLP Specialization", "TensorFlow Developer Certificate"],
    source: "seed",
  }),
  c({
    id: "cand-7",
    name: "Karthik Nair",
    email: "karthik.nair@example.com",
    phone: "+91 94470 88231",
    location: "Kochi, IN",
    age: 34,
    gender: "Male",
    title: "DevOps / Platform Engineer",
    years: 8,
    summary:
      "Platform engineer with deep Kubernetes, Docker and CI/CD expertise, recently supporting ML deployment infrastructure for data teams.",
    skills: ["Docker", "Kubernetes", "MLOps", "Python", "Terraform", "AWS SageMaker", "SQL", "Airflow"],
    education: {
      degree: "B.Tech",
      level: "Bachelors",
      field: "Information Technology",
      school: "NIT Calicut",
      year: 2017,
    },
    experience: [
      {
        company: "Nykaa",
        role: "Platform Engineer",
        start: "2020",
        end: "Present",
        years: 5,
        bullets: [
          "Deployed models as scalable services with monitoring and rollback for the data science org.",
          "Optimised model inference latency and infrastructure cost, cutting GPU spend by 38%.",
          "Built reproducible training pipelines and feature engineering workflows with Airflow.",
        ],
      },
      {
        company: "UST Global",
        role: "DevOps Engineer",
        start: "2017",
        end: "2020",
        years: 3,
        bullets: ["Managed multi-region Kubernetes clusters and CI/CD for 40 microservices."],
      },
    ],
    projects: [
      {
        name: "ModelMesh",
        description: "Self-service model deployment and inference platform with autoscaling and canary rollouts.",
        skills: ["Kubernetes", "MLOps", "Docker"],
      },
    ],
    certifications: ["Certified Kubernetes Administrator", "AWS Certified Machine Learning"],
    source: "seed",
  }),
  c({
    id: "cand-8",
    name: "Meera Joshi",
    email: "meera.joshi@example.com",
    phone: "+91 88790 41123",
    location: "Ahmedabad, IN",
    age: 26,
    gender: "Female",
    title: "Machine Learning Engineer I",
    years: 3,
    summary:
      "Early-career ML engineer working on computer vision and tabular models, comfortable with PyTorch training loops and Docker packaging.",
    skills: ["Python", "PyTorch", "Machine Learning", "Docker", "SQL", "Hugging Face", "NLP"],
    education: {
      degree: "B.E",
      level: "Bachelors",
      field: "Computer Science",
      school: "DAIICT",
      year: 2022,
    },
    experience: [
      {
        company: "Infostretch",
        role: "Machine Learning Engineer",
        start: "2022",
        end: "Present",
        years: 3,
        bullets: [
          "Designed and trained deep learning models for defect detection with 94% precision.",
          "Packaged inference services in Docker and handed off to platform for deployment.",
          "Collaborated with product teams to define offline and online metrics for vision models.",
        ],
      },
    ],
    projects: [
      {
        name: "VisionQC",
        description: "Deep learning inference pipeline for manufacturing quality control with active learning.",
        skills: ["PyTorch", "Python"],
      },
      {
        name: "TicketSort",
        description: "Transformer-based support ticket classifier with retrieval of similar past tickets.",
        skills: ["NLP", "Hugging Face"],
      },
    ],
    certifications: ["TensorFlow Developer Certificate"],
    source: "seed",
  }),
  c({
    id: "cand-9",
    name: "Daniel Fernandes",
    email: "daniel.fernandes@example.com",
    phone: "+91 99870 12045",
    location: "Goa, IN",
    age: 38,
    gender: "Male",
    title: "Backend Engineer",
    years: 12,
    summary:
      "Backend engineer with twelve years in distributed systems and payments, exploring a move into data-intensive and ML-adjacent roles.",
    skills: ["Java", "Python", "SQL", "Docker", "Kafka", "Microservices", "Spark"],
    education: {
      degree: "B.Tech",
      level: "Bachelors",
      field: "Electronics",
      school: "Goa Engineering College",
      year: 2013,
    },
    experience: [
      {
        company: "Razorpay",
        role: "Staff Backend Engineer",
        start: "2018",
        end: "Present",
        years: 7,
        bullets: [
          "Owned payment ledger services processing 4B events annually with strict consistency guarantees.",
          "Built reproducible data pipelines feeding risk models with Kafka and Spark.",
        ],
      },
      {
        company: "Cognizant",
        role: "Software Engineer",
        start: "2013",
        end: "2018",
        years: 5,
        bullets: ["Delivered Java microservices for banking clients across three continents."],
      },
    ],
    projects: [
      {
        name: "LedgerCore",
        description: "Event-sourced ledger with replayable pipeline and audit tooling.",
        skills: ["Java", "Kafka"],
      },
    ],
    certifications: [],
    source: "seed",
  }),
  c({
    id: "cand-10",
    name: "Fatima Sheikh",
    email: "fatima.sheikh@example.com",
    phone: "+91 90210 55673",
    location: "Hyderabad, IN",
    age: 28,
    gender: "Female",
    title: "AI Engineer",
    years: 4,
    summary:
      "AI Engineer bridging data science and language models: builds RAG assistants, evaluation dashboards and experiment tracking for internal AI products.",
    skills: [
      "Python", "LLM", "RAG", "LangChain", "Vector Databases", "NLP", "SQL", "Prompt Engineering", "Statistics", "A/B Testing", "Data Visualization",
    ],
    education: {
      degree: "M.Tech",
      level: "Masters",
      field: "Artificial Intelligence",
      school: "IIIT Hyderabad",
      year: 2021,
    },
    experience: [
      {
        company: "Darwinbox",
        role: "AI Engineer",
        start: "2022",
        end: "Present",
        years: 3,
        bullets: [
          "Built retrieval augmented generation pipelines over enterprise documents for HR policy search.",
          "Designed evaluation harnesses measuring hallucination and grounding quality with human review loops.",
          "Designed and analysed controlled experiments across growth surfaces for assistant adoption.",
        ],
      },
      {
        company: "Tredence",
        role: "Data Science Consultant",
        start: "2021",
        end: "2022",
        years: 1,
        bullets: ["Delivered forecasting and dashboard projects for CPG clients."],
      },
    ],
    projects: [
      {
        name: "PolicyPal",
        description: "Enterprise retrieval chatbot with embedding search, citation grounding and feedback capture.",
        skills: ["LLM", "RAG", "Vector Databases"],
      },
      {
        name: "PromptLab",
        description: "Prompt experiment tracker comparing summarization quality across model versions.",
        skills: ["Prompt Engineering", "Python"],
      },
    ],
    certifications: ["DeepLearning.AI NLP Specialization"],
    source: "seed",
  }),
];
